import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { bundlePreviewRenderer } from './lib/bundle-cms-preview.mjs';
import { makeCmsConfig } from '../cms.config.mjs';

let repo = process.env.GITHUB_REPOSITORY;
if (!repo) {
  try {
    const remote = execFileSync('git', ['remote', 'get-url', 'origin'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
    repo = remote.match(/github\.com[:/]([^/]+\/[^/]+?)(?:\.git)?$/)?.[1];
  } catch { /* An unconnected template can still be edited locally. */ }
}
repo ||= 'slackkai/latentk.com';
const site = JSON.parse(await readFile(new URL('../src/data/site.json', import.meta.url), 'utf8'));
const config = makeCmsConfig({ repo, siteUrl: process.env.SITE_URL || site.url, base: process.env.BASE_PATH || '/' });
// Regenerated from node_modules every time, so nothing stale is deployed.
await rm('public/admin/vendor', { recursive: true, force: true });
await mkdir('public/admin/vendor', { recursive: true });
await cp('node_modules/@sveltia/cms/dist', 'public/admin/vendor', {
  recursive: true, filter: source => !source.endsWith('.map'),
});
await cp('node_modules/@sveltia/cms/LICENSE.txt', 'public/admin/vendor/LICENSE.txt');
// KaTeX renders math in the preview (components.js and notebook-markdown.js share this copy).
await cp('node_modules/katex/dist/katex.min.js', 'public/admin/vendor/katex.min.js');
await cp('node_modules/katex/dist/katex.min.css', 'public/admin/vendor/katex/katex.min.css');
await cp('node_modules/katex/dist/fonts', 'public/admin/vendor/katex/fonts', { recursive: true, filter: source => !/\.(ttf|woff)$/.test(source) });
await cp('node_modules/katex/LICENSE', 'public/admin/vendor/KATEX-LICENSE.txt');
await bundlePreviewRenderer();
// The preview iframe needs its own font declarations and subset files.
await mkdir('public/admin/vendor/wenkai', { recursive: true });
await cp('node_modules/lxgw-wenkai-screen-webfont/lxgwwenkaiscreen.css', 'public/admin/vendor/wenkai/lxgwwenkaiscreen.css');
await cp('node_modules/lxgw-wenkai-screen-webfont/files', 'public/admin/vendor/wenkai/files', { recursive: true });
await cp('node_modules/lxgw-wenkai-screen-webfont/OFL.txt', 'public/admin/vendor/wenkai/OFL.txt');
await cp('node_modules/lxgw-wenkai-screen-webfont/LICENSE', 'public/admin/vendor/wenkai/LICENSE');
// JSON is also valid YAML; no template interpolation of user-controlled values.
await writeFile('public/admin/config.yml', JSON.stringify(config, null, 2) + '\n');
await writeFile('public/admin/preview.css', await previewStylesheet());
console.log(`CMS configured for ${repo} (${config.site_url})`);

/**
 * Reuse site typography and notebook styles in the isolated preview iframe.
 * Imports are replaced with local vendor assets, so this also works with a Pages base.
 */
async function previewStylesheet() {
  const tokens = await readFile(new URL('../src/styles/tokens.css', import.meta.url), 'utf8');
  const global = await readFile(new URL('../src/styles/global.css', import.meta.url), 'utf8');
  const markdown = await readFile(new URL('../src/styles/markdown.css', import.meta.url), 'utf8');
  const overrides = await readFile(new URL('../src/styles/cms-preview.css', import.meta.url), 'utf8');
  const styles = `${global.replace(/^@import\s+[^;]+;/gm, '')}\n${markdown}`.replaceAll('.prose', '[data-rich-text-preview]');
  const imports = ['./vendor/wenkai/lxgwwenkaiscreen.css', './vendor/katex/katex.min.css'].map(url => `@import url('${url}');`).join('\n');
  return `/* Generated by scripts/prepare-cms.mjs. */\n${imports}\n${tokens}\n${styles}\n${overrides}\n`;
}
